### ISSUE TITLE
Integrate scraped course data into audit parser

### ISSUE THREAD

**Issue by tkindy** [tkindy/NUCourse#5]
Depends on #3

Once I have [all of the course data](https://github.com/tkindy/NUCourse/issues/3), I can use it to paint a better picture of a student's audit. Each course number can be matched with a value in the database. I'd also have a much better idea of what a student's program requirements are; I wouldn't have to rely just on the text in the audit to decide what they still had to complete.

## Tasks
- [ ] Connect audit parser to course database
- [ ] Match courses during audit parsing
- [ ] Reconcile program requirements based on database values
